name: Detect Reverts and Verify Commit Message

on: [push]

jobs:
  detect_reverts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Git
      run: sudo apt-get install git

    - name: Run detect_reverts.py
      id: detect_reverts
      run: |
        NEW_COMMIT_HASH=$(git rev-parse HEAD)
        REVERT_COMMIT=$(python scripts/detect_reverts.py)
        echo "::set-output name=revert_commit::$REVERT_COMMIT"
      env:
        NEW_COMMIT_HASH: ${{ github.sha }}

    - name: Check commit message
      if: steps.detect_reverts.outputs.revert_commit != ''
      run: |
        REVERT_COMMIT=${{ steps.detect_reverts.outputs.revert_commit }}
        if [[ $REVERT_COMMIT == "None" || $REVERT_COMMIT == "" ]]; then
          echo "No revert commit detected"
          exit 0
        fi
        COMMIT_MESSAGE=$(git log -1 --pretty=%B $REVERT_COMMIT)
        if [[ ! $COMMIT_MESSAGE =~ ^Revert ]]; then
          echo "Error: Revert commit detected: $REVERT_COMMIT with incorrect message, expected start with 'Revert'"
          exit 1
        else
          echo "Revert commit detected: $REVERT_COMMIT with correct message"
        fi
